### ISSUE TITLE
Error handling?

### ISSUE THREAD

**Issue by akashnimare** [JamesKyburz/dialogs#21]
Great module. I am using it load the window url. Here is the code - 

``` javascript
            var dialogs = require('dialogs')()
            dialogs.prompt('Add your Domain', function (ok) {
            db.push("/domain", ok);
            window.location.href = ok; 
```

Now how can I callback if user clicks on cancel? I want to show alert on cancel.

**Comment by JamesKyburz** [comment]
If cancel is clicked then the value of ok will be undefined.
Otherwise it will either by an empty string or the value entered.

It works like the synchronous window.prompt function, with the exception of window.prompt returning null on cancel.

So I would suggest checking for [truthy](https://en.wikipedia.org/wiki/JavaScript_syntax), this would only handle the scenario of entering a value and OK being clicked.

```
dialogs.prompt('Add your Domain', function (ok) {
   if (ok) {
     db.push("/domain", ok)
     window.location.href = ok
   }
})
```

**Comment by akashnimare** [comment]
Thanks man. It worked :+1:
